/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Users;

import JPA.Persona;
import JPA.Rol;
import JPA.TipoIdentificacion;
import JPA.TipoPersona;
import JPA.Usuario;
import Util.GeneralException;
import com.mysql.cj.Session;
import static com.sun.xml.internal.ws.spi.db.BindingContextFactory.LOGGER;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.util.List;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author Juan Cubillos
 */
public class User extends javax.swing.JFrame {

    class UppercaseDocumentFilter extends DocumentFilter {

        @Override
        public void insertString(DocumentFilter.FilterBypass fb, int offset,
                String text, AttributeSet attr) throws BadLocationException {
            fb.insertString(offset, text.toUpperCase(), attr);
        }

        @Override
        public void replace(DocumentFilter.FilterBypass fb, int offset, int length,
                String text, AttributeSet attrs) throws BadLocationException {
            fb.replace(offset, length, text.toUpperCase(), attrs);
        }
    }

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        DocumentFilter filter = new User.UppercaseDocumentFilter();
        ((AbstractDocument) jTextFieldUsuario.getDocument()).setDocumentFilter(filter);
        EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("com.Unidad2_Fase3_JSCG_Unidad2_Fase3_JSCG_jar_1.0PU");
        EntityManager em = entityManagerFactory.createEntityManager();
        Query queryTipoIdentificacion = em.createNamedQuery("TipoIdentificacion.findAll");
        jComboBoxTipoDocumento.removeAllItems();
        List<TipoIdentificacion> listTipoIdentificacion = queryTipoIdentificacion.getResultList();
        listTipoIdentificacion.forEach((TipoIdentificacion tipoIdentificacion) -> {
            jComboBoxTipoDocumento.addItem(tipoIdentificacion.getDescripcion());
        });
        Query queryRol = em.createNamedQuery("Rol.findAll");
        jComboBoxRol.removeAllItems();
        List<Rol> listRol = queryRol.getResultList();
        listRol.forEach((rol) -> {
            jComboBoxRol.addItem(rol.getDescripcion());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAyuda = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelFechaNacimiento = new javax.swing.JLabel();
        jLabelNumeroDocumento = new javax.swing.JLabel();
        jTextFieldNumeroDocumento = new javax.swing.JTextField();
        jLabelTipoDocumento = new javax.swing.JLabel();
        jComboBoxTipoDocumento = new javax.swing.JComboBox<>();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelClave = new javax.swing.JLabel();
        jTextFieldClave = new javax.swing.JTextField();
        jLabelRol = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jButtonRegistrarUsuario = new javax.swing.JButton();
        jDateChooserFechaNacimiento = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administración de usuarios");

        jLabelAyuda.setText("Bienvenido señor usuario, usted podra administrar sus usuarios en esta pantalla.");

        jLabelNombre.setText("Nombre");

        jLabelApellido.setText("Apellido");

        jLabelEdad.setText("Edad");

        jTextFieldEdad.setText("0");
        jTextFieldEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEdadKeyPressed(evt);
            }
        });

        jLabelFechaNacimiento.setText("Fecha nacimiento");

        jLabelNumeroDocumento.setText("Número documento");

        jLabelTipoDocumento.setText("Tipo documento");

        jComboBoxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelUsuario.setText("Usuario");

        jLabelClave.setText("Contraseña");

        jLabelRol.setText("Rol");

        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonRegistrarUsuario.setText("Registrar");
        jButtonRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAyuda)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUsuario)
                                .addGap(93, 93, 93)
                                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelApellido)
                                    .addComponent(jLabelEdad)
                                    .addComponent(jLabelRol))
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonRegistrarUsuario)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldNombre)
                                            .addComponent(jTextFieldApellido)
                                            .addComponent(jTextFieldEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelNumeroDocumento)
                                            .addComponent(jLabelTipoDocumento)
                                            .addComponent(jLabelFechaNacimiento)
                                            .addComponent(jLabelClave))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNumeroDocumento)
                            .addComponent(jComboBoxTipoDocumento, 0, 236, Short.MAX_VALUE)
                            .addComponent(jTextFieldClave)
                            .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEdad)
                        .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAyuda)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNumeroDocumento)
                                    .addComponent(jTextFieldNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelApellido)
                                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTipoDocumento)
                                    .addComponent(jComboBoxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabelFechaNacimiento)))
                        .addGap(6, 6, 6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClave)
                    .addComponent(jTextFieldClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRol))
                .addGap(28, 28, 28)
                .addComponent(jButtonRegistrarUsuario)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
        ValidateFormRegisterUser();
        try {
            EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("com.Unidad2_Fase3_JSCG_Unidad2_Fase3_JSCG_jar_1.0PU");
            EntityManager em = entityManagerFactory.createEntityManager();
            int countUser = ((Number) em.createNamedQuery("Usuario.findByUsuarioCount").setParameter("usuario", jTextFieldUsuario.getText()).getSingleResult()).intValue();
            if (countUser > 0) {
                jTextFieldUsuario.setText("");
                JOptionPane.showMessageDialog(null, "El nombre del usuario ya fue registrado", "Error", JOptionPane.ERROR_MESSAGE);
                throw new GeneralException("El nombre del usuario ya fue registrado");
            }
            em.close();
        } catch (GeneralException | HeadlessException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
        EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("com.Unidad2_Fase3_JSCG_Unidad2_Fase3_JSCG_jar_1.0PU");
        EntityManager em = entityManagerFactory.createEntityManager();
        EntityTransaction entityTransaction = em.getTransaction();
        try {
            entityTransaction.begin();
            Persona persona = new Persona();
            persona.setNombre(jTextFieldNombre.getText());
            persona.setApellido(jTextFieldApellido.getText());
            persona.setEdad(Integer.parseInt(jTextFieldEdad.getText()));
            persona.setFechaNacimiento(jDateChooserFechaNacimiento.getDate());
            final int TIPO_EMPLEADO = 1;
            TipoPersona tipoPersona = new TipoPersona();
            tipoPersona.setIdTipoPersona(TIPO_EMPLEADO);
            persona.setIdTipoPersona(tipoPersona);
            TipoIdentificacion tipoIdentificacion = new TipoIdentificacion();
            tipoIdentificacion.setIdTipoIdentificacion(jComboBoxTipoDocumento.getSelectedIndex() + 1);
            persona.setIdTipoIdentificacion(tipoIdentificacion);
            persona.setIdentificacion(jTextFieldNumeroDocumento.getText());
            em.persist(persona);
            Usuario usuario = new Usuario();
            usuario.setUsuario(jTextFieldUsuario.getText());
            usuario.setClave(jTextFieldClave.getText());
            usuario.setBloqueado(false);
            usuario.setIdPersona(persona);
            Rol rol = new Rol(jComboBoxRol.getSelectedIndex() + 1);
            usuario.setIdRol(rol);
            em.persist(usuario);
            entityTransaction.commit();
            em.close();
            JOptionPane.showMessageDialog(null, "El usuario: " + usuario.getUsuario() + ", con nombre: " + persona.getNombre() + ", fue registrado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            CleanFormRegisterUser();
        } catch (HeadlessException | NumberFormatException ex) {
            entityTransaction.rollback();
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Atención ocurrio un error al guardar el usuario, error especifico: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRegistrarUsuarioActionPerformed

    private void jTextFieldEdadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || key == KeyEvent.VK_BACK_SPACE) {
            jTextFieldEdad.setEditable(true);
            jTextFieldEdad.setBackground(Color.GREEN);
        } else {
            jTextFieldEdad.setEditable(false);
            jTextFieldEdad.setBackground(Color.RED);
        }
    }//GEN-LAST:event_jTextFieldEdadKeyPressed

    private void ValidateFormRegisterUser() {
        try {
            if (jTextFieldNombre.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "El nombre de la persona es obligatorio, para registrarse como usuario", "Error", JOptionPane.ERROR_MESSAGE);
                throw new GeneralException("El nombre de la persona es obligatorio, para registrarse como usuario");
            }
            if (jTextFieldApellido.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "El apellido de la persona es obligatorio, para registrarse como usuario", "Error", JOptionPane.ERROR_MESSAGE);
                throw new GeneralException("El apellido de la persona es obligatorio, para registrarse como usuario");
            }
            if (jTextFieldNumeroDocumento.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "El número de documento de la persona es obligatorio, para registrarse como usuario", "Error", JOptionPane.ERROR_MESSAGE);
                throw new GeneralException("El número de documento de la persona es obligatorio, para registrarse como usuario");
            }
            if (jComboBoxTipoDocumento.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(null, "El tipo de documento es obligatorio, para registrarse como usuario", "Error", JOptionPane.ERROR_MESSAGE);
                throw new GeneralException("El tipo de documento es obligatorio, para registrarse como usuario");
            }
            if (jTextFieldEdad.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "La edad de la persona es obligatoria, para registrarse como usuario", "Error", JOptionPane.ERROR_MESSAGE);
                throw new GeneralException("La edad de la persona es obligatoria, para registrarse como usuario");
            }
            if (jDateChooserFechaNacimiento.getDate() == null) {
                JOptionPane.showMessageDialog(null, "La fecha de nacimiento es obligatoria, para registrarse como usuario", "Error", JOptionPane.ERROR_MESSAGE);
                throw new GeneralException("La fecha de nacimiento es obligatoria, para registrarse como usuario");
            }
            if (jTextFieldUsuario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "El usuario es obligatorio, para registrarse como usuario", "Error", JOptionPane.ERROR_MESSAGE);
                throw new GeneralException("El usuario es obligatorio, para registrarse como usuario");
            }
            if (jTextFieldClave.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "La clave del usuario es obligatoria, para registrarse como usuario", "Error", JOptionPane.ERROR_MESSAGE);
                throw new GeneralException("La clave del usuario es obligatoria, para registrarse como usuario");
            }
            if (jComboBoxRol.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(null, "El rol del usuario obligatorio, para registrarse como usuario", "Error", JOptionPane.ERROR_MESSAGE);
                throw new GeneralException("El rol del usuario obligatorio, para registrarse como usuario");
            }
        } catch (GeneralException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void CleanFormRegisterUser() {
        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldNumeroDocumento.setText("");
        jComboBoxTipoDocumento.setSelectedIndex(0);
        jTextFieldEdad.setText("");
        jDateChooserFechaNacimiento.setDate(null);
        jTextFieldUsuario.setText("");
        jTextFieldClave.setText("");
        jComboBoxRol.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrarUsuario;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JComboBox<String> jComboBoxTipoDocumento;
    private com.toedter.calendar.JDateChooser jDateChooserFechaNacimiento;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelAyuda;
    private javax.swing.JLabel jLabelClave;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFechaNacimiento;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumeroDocumento;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelTipoDocumento;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldClave;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroDocumento;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

}
