
import JPA.Usuario;
import Util.GeneralException;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Juan Cubillos
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        ImageIcon logo = new ImageIcon();
        setIconImage(logo.getImage());
        jPasswordFieldPasswordUser.setEchoChar((char) '*');
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width /2 - getWidth() / 2, size.height / 2 - getHeight() /2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWelcomeMessage = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jButtonLogIn = new javax.swing.JButton();
        jPasswordFieldPasswordUser = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Soluciónalo S.A.S");
        setMaximumSize(new java.awt.Dimension(510, 300));
        setMinimumSize(new java.awt.Dimension(510, 300));
        setName("frameLogin"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(510, 300));

        jLabelWelcomeMessage.setText("Bienvenido señor usuario, por favor digite su usuario y contraseña para iniciar sesión");
        jLabelWelcomeMessage.setName("jLabelWelcomeMessage"); // NOI18N

        jLabelUser.setText("Usuario");
        jLabelUser.setName("jLabelUser"); // NOI18N

        jTextFieldUser.setName("jTextFieldUser"); // NOI18N

        jLabelPassword.setText("Contraseña");
        jLabelPassword.setName("jLabelPassword"); // NOI18N

        jButtonLogIn.setText("Iniciar sesión");
        jButtonLogIn.setName("jButtonLogIn"); // NOI18N
        jButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogInActionPerformed(evt);
            }
        });

        jPasswordFieldPasswordUser.setName("jPasswordFieldPasswordUser"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelWelcomeMessage)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonLogIn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPassword)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordFieldPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUser)
                                .addGap(40, 40, 40)
                                .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelWelcomeMessage)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUser)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordFieldPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonLogIn)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jLabelWelcomeMessage.getAccessibleContext().setAccessibleName("jLabelWelcomeMessage");
        jLabelUser.getAccessibleContext().setAccessibleName("jLabelUser");
        jTextFieldUser.getAccessibleContext().setAccessibleName("jTextFieldUser");
        jLabelPassword.getAccessibleContext().setAccessibleName("jLabelPassword");
        jButtonLogIn.getAccessibleContext().setAccessibleName("jButtonLogIn");
        jPasswordFieldPasswordUser.getAccessibleContext().setAccessibleName("jPasswordFieldPasswordUser");

        getAccessibleContext().setAccessibleName("frameLogin");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("UseSpecificCatch")
    private void jButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogInActionPerformed
        // TODO add your handling code here:
        String passwordUser = new String(jPasswordFieldPasswordUser.getPassword());
        if (passwordUser.isEmpty() || jTextFieldUser.getText().isEmpty()) {
            try {
                JOptionPane.showMessageDialog(null, "Por favor digite su usuario y su contraseña", "Error", JOptionPane.ERROR_MESSAGE);
                throw new GeneralException("Por favor digite su usuario y su contraseña");
            } catch (GeneralException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("com.Unidad2_Fase3_JSCG_Unidad2_Fase3_JSCG_jar_1.0PU");
                EntityManager em = entityManagerFactory.createEntityManager();
                Query queryUser = em.createNamedQuery("Usuario.findByUsuarioAndClave");
                queryUser.setParameter("usuario", jTextFieldUser.getText());
                queryUser.setParameter("clave", passwordUser);
                Usuario usuario = (Usuario) queryUser.getSingleResult();
                JOptionPane.showMessageDialog(null, "Usuario: " + usuario.getUsuario(), "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
                Menu menu = new Menu();
                menu.setVisible(true);
                setVisible(false);
            } catch (Exception ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                jTextFieldUser.setText("");
                jPasswordFieldPasswordUser.setText("");
                JOptionPane.showMessageDialog(null, "Usuario o contraseña invalidos", "Error", JOptionPane.ERROR_MESSAGE);
                try {
                    throw new GeneralException("Usuario o contraseña invalidos");
                } catch (GeneralException ex1) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }
        }
    }//GEN-LAST:event_jButtonLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogIn;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelWelcomeMessage;
    private javax.swing.JPasswordField jPasswordFieldPasswordUser;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
